/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sgc.iframe;

import com.sgc.JComPz.Item;
import com.sgc.bean.TemplateType;
import com.sgc.dao.TemplateTypeDaoProxy;
import com.sgc.dao.TemplateTypeFactory;
import com.sgc.geometric.ConnRegion;
import com.sgc.main.LicensePR;
import com.sgc.photo.*;
import com.sgc.res.ExcisionUnit;
import com.sgc.res.RadonRes;
import com.sgc.service.*;
import com.sgc.util.MyDocument;
import com.sgc.util.Util;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.List;

/**
 *
 * @author SODT
 */
public class TmpMakeFrame extends JInternalFrame {
    public static String[] TEMPLATE_TYPE_NAME=new String[]{"CHN","ALPH","NUM"};
    private BufferedImage sourceImage;                      // 图像源文件
    private BufferedImage[] procImages=new BufferedImage[2];// 处理流程文件
    private List<ExcisionUnit> excisions;                            // 字符分割结果
    private BufferedImage[] stdChars=new BufferedImage[7];
    DefaultComboBoxModel cbbsModel;

    /**
     * Creates new form 新建JInternalFrame
     */
    public TmpMakeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jPanel4 = new JPanel();
        jPanel5 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        jPanel3 = new JPanel();
        jPanel6 = new JPanel();
        jLabel2 = new JLabel();
        jPanel16 = new JPanel();
        stdCharsPanel[0]=jPanel16;
        jLabel11 = new JLabel();
        jTextField1 = new JTextField();
        jComboBox1 = new JComboBox<>();
        jLabel12 = new JLabel();
        jButton4 = new JButton();
        jPanel14 = new JPanel();
        jLabel6 = new JLabel();
        jPanel17 = new JPanel();
        stdCharsPanel[1]=jPanel17;
        jLabel13 = new JLabel();
        jTextField2 = new JTextField();
        jComboBox2 = new JComboBox<>();
        jLabel14 = new JLabel();
        jButton5 = new JButton();
        jPanel24 = new JPanel();
        jLabel17 = new JLabel();
        jPanel25 = new JPanel();
        stdCharsPanel[2]=jPanel25;
        jLabel18 = new JLabel();
        jTextField4 = new JTextField();
        jComboBox4 = new JComboBox<>();
        jLabel19 = new JLabel();
        jButton7 = new JButton();
        jPanel26 = new JPanel();
        jLabel20 = new JLabel();
        jPanel27 = new JPanel();
        stdCharsPanel[5]=jPanel27;
        jLabel21 = new JLabel();
        jTextField5 = new JTextField();
        jComboBox5 = new JComboBox<>();
        jLabel22 = new JLabel();
        jButton8 = new JButton();
        jPanel30 = new JPanel();
        jLabel26 = new JLabel();
        jPanel31 = new JPanel();
        stdCharsPanel[3]=jPanel31;
        jLabel27 = new JLabel();
        jTextField7 = new JTextField();
        jComboBox7 = new JComboBox<>();
        jLabel28 = new JLabel();
        jButton10 = new JButton();
        jPanel32 = new JPanel();
        jLabel29 = new JLabel();
        jPanel33 = new JPanel();
        stdCharsPanel[4]=jPanel33;
        jLabel30 = new JLabel();
        jTextField8 = new JTextField();
        jComboBox8 = new JComboBox<>();
        jLabel31 = new JLabel();
        jButton11 = new JButton();
        jPanel34 = new JPanel();
        jLabel32 = new JLabel();
        jPanel35 = new JPanel();
        stdCharsPanel[6]=jPanel35;
        jLabel33 = new JLabel();
        jTextField9 = new JTextField();
        jComboBox9 = new JComboBox<>();
        jLabel34 = new JLabel();
        jButton12 = new JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(880, 640));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(370, 300));

        jLabel1.setText("字符分割结果");

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("图像选择");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("模板制作");
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton2ActionPerformed(e);
            }
        });

        jButton3.setText("返回");
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doDefaultCloseAction();
            }
        });

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel1)
                                .addContainerGap(157, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(800, 300));

        jPanel6.setPreferredSize(new java.awt.Dimension(110, 280));

        jLabel2.setText("字符1");

        GroupLayout jPanel16Layout = new GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
                jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
                jPanel16Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel11.setText("字符编号");

        jTextField1.setText("川01");
        jTextField1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel12.setText("字符类型");

        jButton4.setText("保存");

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel2))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel11))
                                                        .addComponent(jPanel16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel12)
                                                                        .addComponent(jButton4))))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel16, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
        );

        jPanel14.setPreferredSize(new java.awt.Dimension(110, 280));

        jLabel6.setText("字符2");

        GroupLayout jPanel17Layout = new GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
                jPanel17Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
                jPanel17Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel13.setText("字符编号");

        jTextField2.setText("901");
        jTextField2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });


        jLabel14.setText("字符类型");

        jButton5.setText("保存");

        GroupLayout jPanel14Layout = new GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel14Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel6))
                                        .addGroup(jPanel14Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel14Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel13))
                                                        .addComponent(jPanel17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel14Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel14Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel14)
                                                                        .addComponent(jButton5))))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jPanel17, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
        );

        jPanel24.setPreferredSize(new java.awt.Dimension(110, 280));

        jLabel17.setText("字符3");

        GroupLayout jPanel25Layout = new GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
                jPanel25Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
                jPanel25Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel18.setText("字符编号");

        jTextField4.setText("901");
        jTextField4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });


        jLabel19.setText("字符类型");

        jButton7.setText("保存");

        GroupLayout jPanel24Layout = new GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
                jPanel24Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel24Layout.createSequentialGroup()
                                .addGroup(jPanel24Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel24Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel17))
                                        .addGroup(jPanel24Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel24Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel24Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel18))
                                                        .addComponent(jPanel25, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel24Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel24Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel24Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel24Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel19)
                                                                        .addComponent(jButton7))))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
                jPanel24Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel24Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jPanel25, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))
        );

        jPanel26.setPreferredSize(new java.awt.Dimension(110, 280));

        jLabel20.setText("字符6");

        GroupLayout jPanel27Layout = new GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
                jPanel27Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
                jPanel27Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel21.setText("字符编号");

        jTextField5.setText("901");
        jTextField5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });


        jLabel22.setText("字符类型");

        jButton8.setText("保存");

        GroupLayout jPanel26Layout = new GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
                jPanel26Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGroup(jPanel26Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel20))
                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel26Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel21))
                                                        .addComponent(jPanel27, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel26Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel26Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel22)
                                                                        .addComponent(jButton8))))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
                jPanel26Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel27, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))
        );

        jPanel30.setPreferredSize(new java.awt.Dimension(110, 280));

        jLabel26.setText("字符4");

        GroupLayout jPanel31Layout = new GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
                jPanel31Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
                jPanel31Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel27.setText("字符编号");

        jTextField7.setText("901");
        jTextField7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });


        jLabel28.setText("字符类型");

        jButton10.setText("保存");

        GroupLayout jPanel30Layout = new GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
                jPanel30Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel30Layout.createSequentialGroup()
                                .addGroup(jPanel30Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel30Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel26))
                                        .addGroup(jPanel30Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel30Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel30Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel27))
                                                        .addComponent(jPanel31, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel30Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel30Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel30Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel30Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jComboBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel28)
                                                                        .addComponent(jButton10))))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
                jPanel30Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel30Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel26)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jPanel31, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10))
        );

        jPanel32.setPreferredSize(new java.awt.Dimension(110, 280));

        jLabel29.setText("字符5");

        GroupLayout jPanel33Layout = new GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
                jPanel33Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
                jPanel33Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel30.setText("字符编号");

        jTextField8.setText("901");
        jTextField8.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });


        jLabel31.setText("字符类型");

        jButton11.setText("保存");

        GroupLayout jPanel32Layout = new GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
                jPanel32Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel32Layout.createSequentialGroup()
                                .addGroup(jPanel32Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel32Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel29))
                                        .addGroup(jPanel32Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel32Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel32Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel30))
                                                        .addComponent(jPanel33, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel32Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel32Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel32Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel32Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jComboBox8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel31)
                                                                        .addComponent(jButton11))))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel32Layout.setVerticalGroup(
                jPanel32Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel32Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel29)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel33, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11))
        );

        jPanel34.setPreferredSize(new java.awt.Dimension(110, 280));

        jLabel32.setText("字符7");

        GroupLayout jPanel35Layout = new GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
                jPanel35Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel35Layout.setVerticalGroup(
                jPanel35Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel33.setText("字符编号");

        jTextField9.setText("901");
        jTextField9.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });


        jLabel34.setText("字符类型");

        jButton12.setText("保存");

        GroupLayout jPanel34Layout = new GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
                jPanel34Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel34Layout.createSequentialGroup()
                                .addGroup(jPanel34Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel34Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel32))
                                        .addGroup(jPanel34Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel34Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel34Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel33))
                                                        .addComponent(jPanel35, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel34Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel34Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel34Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addGroup(jPanel34Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jComboBox9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel34)
                                                                        .addComponent(jButton12))))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
                jPanel34Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel34Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel32)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel35, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel34)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12))
        );

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel14, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel24, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel30, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel32, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel26, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel34, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel14, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel24, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jPanel30, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())
                                        .addComponent(jPanel32, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                        .addComponent(jPanel26, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                        .addComponent(jPanel34, GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        /*将按钮对象的引用保存到按钮数组*/
        saveBtns[0]=jButton4;
        saveBtns[1]=jButton5;
        saveBtns[2]=jButton7;
        saveBtns[3]=jButton10;
        saveBtns[4]=jButton11;
        saveBtns[5]=jButton8;
        saveBtns[6]=jButton12;
        for(int i=0;i<saveBtns.length;i++){
            saveBtns[i].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    saveStdChar(e);
                }
            });
        }
        /*将复选框对象的引用保存到复选框数组*/
        cbbs[0]=jComboBox1;
        cbbs[1]=jComboBox2;
        cbbs[2]=jComboBox4;
        cbbs[3]=jComboBox7;
        cbbs[4]=jComboBox8;
        cbbs[5]=jComboBox5;
        cbbs[6]=jComboBox9;
        /**
         * templateType = new JComboBox();//创建书籍类别下拉框
         bookTypeModel= (DefaultComboBoxModel)templateType.getModel();//设置类别模型

         // 数据库访问
         TemplateTypeDaoProxy dao= (TemplateTypeDaoProxy)TemplateTypeFactory.getDaoInstance();

         List<TemplateType> list=dao.findAll();//从数据库中取出图书类别
         for(int i=0;i<list.size();i++){		//遍历图书类别
         TemplateType booktype=list.get(i);//获得图书类别
         Item item=new Item();//实例化图书类别选项
         item.setId(booktype.getType());//设置图书类别编号
         item.setName(booktype.getTypeName());//设置图书类别名称
         bookTypeModel.addElement(item);//添加图书类别元素
         }
         */

        TemplateTypeDaoProxy dao= (TemplateTypeDaoProxy) TemplateTypeFactory.getDaoInstance();// 数据库访问
        List<TemplateType> list=dao.findAll();//从数据库中取出图书类别
        for(int i=0;i<cbbs.length;i++){
            cbbsModel=(DefaultComboBoxModel)cbbs[i].getModel();
            for(int j=0;j<list.size();j++){		//遍历图书类别
                TemplateType booktype=list.get(j);//获得图书类别
                Item item=new Item();//实例化图书类别选项
                item.setId(booktype.getType());//设置图书类别编号
                item.setName(booktype.getTypeName());//设置图书类别名称
                cbbsModel.addElement(item);//添加图书类别元素
            }
        }

        /*将复选框对象的引用保存到复选框数组*/
        texts[0]=jTextField1;
        texts[1]=jTextField2;
        texts[2]=jTextField4;
        texts[3]=jTextField7;
        texts[4]=jTextField8;
        texts[5]=jTextField5;
        texts[6]=jTextField9;

        pack();
        setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void saveStdChar(ActionEvent e) {
        for(int i=0;i<saveBtns.length;i++) {
            if (saveBtns[i]==e.getSource()){
                int ctypeid=cbbs[i].getSelectedIndex();
                String ctype=TEMPLATE_TYPE_NAME[ctypeid];
                String cnumname=texts[i].getText();
                if("".equals(cnumname.trim())) return;
                String fname= LicensePR.class.getResource("/templates/").getPath();
                fname+=ctype+"_"+cnumname;try{
                    AbstractBufferedImageOp.writeImageFile(stdChars[i],fname);
                }catch(IOException exp){}
            }
        }
    }

    private void jButton2ActionPerformed(ActionEvent e) {
        procImages[0]=locObj(sourceImage);          //定位
        procImages[1]=skewCorrect(procImages[0]);   //倾斜校正
        excisions=charExc(procImages[1]);           //字符分割
        paintCharExcRes();                          //绘制字符分割结果
    }

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            Util.setFileTypeFilter(chooser);
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            if (null != f) {
                sourceImage = ImageIO.read(f);
                paintSrcImg();
            }

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    public void paintSrcImg(){
        Graphics2D g2d=(Graphics2D)jPanel1.getGraphics();
        if(null==sourceImage) return;
        int width=512;
        int height=400;
        Image buffImage=createImage(width,height);
        Graphics2D g=(Graphics2D)buffImage.getGraphics();
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, width, height);
        ZoomFilter zoomFilter=new ZoomFilter(width,height);
        BufferedImage image=zoomFilter.zoom(sourceImage);
        g.drawImage(image,0,0,512,400,this);
        g2d.drawImage(buffImage,0,0,this);
    }
    /**
     * 车牌定位
     * @param image
     * @return
     */
    private BufferedImage locObj(BufferedImage image){
        if(null==image){
            JOptionPane.showMessageDialog(this,"请选择图像源文件");
            return null;
        }
        // 彩色图像直方图均衡化
        HistogramEFilter histogramEFilter = new HistogramEFilter();
        BufferedImage destImage = histogramEFilter.filter(image, null);
        // 高斯模糊处理——去除图像细节,保留图像主要特征
        GaussianBlurFilter gaussianBlurFilter = new GaussianBlurFilter();
        destImage = gaussianBlurFilter.filter(destImage, null);
        // 分级灰度化
        ColorPicker[] colorPickers = new ColorPicker[4];
        colorPickers[0] = new BlueColorPicker(190f, 245f, 0.35f, 1f, 0.3f, 1f);
        colorPickers[1] = new YellowColorPicker(25f, 55f, 0.35f, 1f, 0.3f, 1f);
        colorPickers[2] = new WhiteColorPicker(0, 0, 0, 0.1f, 0.91f, 1f);
        colorPickers[3] = new BlackColorPicker(0, 0, 0, 0, 0, 0.35f);
        LayerGrayFilter layerGrayFilter = new LayerGrayFilter(colorPickers);
        destImage = layerGrayFilter.filter(destImage, null);
        // 分层二值化
        BufferedImage[] images = layerGrayFilter.binaryImage();
        // 灰度化
        com.sgc.photo.GrayFilter grayFilter = new com.sgc.photo.GrayFilter();
        BufferedImage middleSection = grayFilter.filter(image, null);
        int[][] se=new int[][] {{0,0,0,0,0,0,0,0,0,0,0,0,0},
                {0,0,0,0,0,7,7,7,0,0,0,0,0},
                {0,0,0,0,7,8,9,8,7,0,0,0,0},
                {0,0,0,7,8,9,10,9,8,7,0,0,0},
                {0,0,7,8,9,10,11,10,9,8,7,0,0},
                {0,7,8,9,10,11,12,11,10,9,8,7,0},
                {7,8,9,10,11,12,12,12,11,10,9,8,7},
                {0,7,8,9,10,11,12,11,10,9,8,7,0},
                {0,0,7,8,9,10,11,10,9,8,7,0,0},
                {0,0,0,7,8,9,10,9,8,7,0,0,0},
                {0,0,0,0,7,8,9,8,7,0,0,0,0},
                {0,0,0,0,0,7,7,7,0,0,0,0,0},
                {0,0,0,0,0,0,0,0,0,0,0,0,0}};
        // 高帽变换
        HatFilter hatFilter=new HatFilter();
        middleSection=hatFilter.onTopHat(middleSection,se);
        // E算子垂直边缘检测
        EOperatorEdgeDet eOperatorEdgeDet = new EOperatorEdgeDet();
        middleSection = eOperatorEdgeDet.filter(middleSection, null);
        // 二值化
        BinaryFilter binaryFilter = new BinaryFilter(BinaryFilter.SHIFT_THRESHOLD);
        middleSection = binaryFilter.filter(middleSection, null);

        // 连通区域检测
        ConnRegDet connRegDet = new ConnRegDet();
        java.util.List<ConnRegion> res = connRegDet.findConnRegs(images, middleSection);
//        System.out.println("1.连通区域数:" + res.size());

        FacticityValidator facticityValidator=new FacticityValidator();
        // 重新获取遍历器
        res=facticityValidator.validate(image,res);
//        System.out.println("2.候选区域数量:"+res.size());
        int size=res.size();
        if(size<1) {
            res=kwfcmLocObj(image);
//            System.out.println(res);
//            System.out.println("2.1候选区域数量:"+res.size());
            res=facticityValidator.validate(image,res);

        }
        // 第二层检查结果
//        System.out.println("3.候选区域数量:"+res.size());

        destImage= connRegDet.show(image,res);
        destImage=binaryFilter.filter(destImage,null);
        ObjRegDet objRegDet=new ObjRegDet();
        ConnRegion connRegion = res.get(0);
        middleSection= objRegDet.getObjReg(image,connRegion);
        return  middleSection;
    }
    private List<ConnRegion> kwfcmLocObj(BufferedImage image){
        PictureEnhanced pictureEnhanced=new PictureEnhanced();
        BufferedImage destImage=pictureEnhanced.enhance(image);
        BufferedImage middleSection=destImage;
        //边缘检测
        MSEEdgeDet mseEdgeDet=new MSEEdgeDet();
        middleSection=mseEdgeDet.prewittEdge(destImage);
        destImage=middleSection;
        //粗步去噪
        LicensePlateDenoise licensePlateDenoise=new LicensePlateDenoise();
        middleSection=licensePlateDenoise.preDenoise(middleSection);
        // 精确去噪
        middleSection=licensePlateDenoise.denoise(middleSection);
        //灰度能量聚类,去除为车牌边缘图
        GrayEnergyCluster grayEnergyCluster=new GrayEnergyCluster(7,11);
        middleSection=grayEnergyCluster.cluster(middleSection,destImage);
        // 图像二值化
        BinaryFilter binaryFilter=new BinaryFilter();
        binaryFilter.setThresholdType(BinaryFilter.OSTU_THRESHOLD);
        destImage=binaryFilter.filter(middleSection,null);
        middleSection=destImage;
        //水平聚类线性探测法
        ConnRegDet connRegDet=new ConnRegDet();
        middleSection=connRegDet.horizontalClusterSearch(destImage,24,0.60);
        //形态学操作
        int[][] C=new int[][]{ {1,1,1,1,1,1,1,1,1,1,1},
                {1,1,1,1,1,1,1,1,1,1,1},
                {1,1,1,1,1,1,1,1,1,1,1},
                {1,1,1,1,1,1,1,1,1,1,1},
                {1,1,1,1,1,1,1,1,1,1,1}};
        // 开运算
        CloseFilter closeFilter=new CloseFilter();
        closeFilter.setStructureElements(C);
        middleSection=closeFilter.filter(middleSection,null);
        destImage=middleSection;
        middleSection=licensePlateDenoise.denoiseConn(middleSection);
        List<ConnRegion> list=connRegDet.findConnRegs(middleSection);
        return list;
    }

    /**
     * 车牌倾斜校正
     * @param image
     * @return
     */
    private BufferedImage skewCorrect(BufferedImage image){
        // 彩色图像灰度化
        com.sgc.photo.GrayFilter grayFilter=new com.sgc.photo.GrayFilter();
        BufferedImage destImage=grayFilter.filter(image,null);

        //测试-图像转置
        TransposeFilter transposeFilter=new TransposeFilter();
        destImage=transposeFilter.filter(destImage,null);
        // 二值化
        BinaryFilter binaryFilter=new BinaryFilter();
        binaryFilter.setThresholdType(BinaryFilter.SHIFT_THRESHOLD);
        destImage=binaryFilter.filter(destImage,null);
        // 测试 多结构元素边缘检测
        MSEEdgeDet mseEdgeDet=new MSEEdgeDet();
        destImage=mseEdgeDet.filter(destImage,null);
        //倾斜校正
        // radon直线检测(图像倾斜)-水平方向检测
        RadonFilter radonFilter=new RadonFilter();
        RadonRes radonRes=radonFilter.radon(destImage,-45,45,1);
        RotationFilter rotationFilter=new RotationFilter();
        double dipAngle=radonRes.getDipAngle();
        dipAngle=45==dipAngle?0:dipAngle;
        dipAngle=-45==dipAngle?0:dipAngle;

        //垂直方向检测
        /*第一步:灰度化*/
        BufferedImage middleSection=grayFilter.filter(image,null);
        /*第二步:二值化*/
        middleSection=binaryFilter.filter(middleSection,null);
        /*第三步:边缘检测*/
        middleSection=mseEdgeDet.filter(middleSection,null);
        /*第四步:倾斜角度检测*/
        radonRes=radonFilter.radon(middleSection,-10,10,1);
        double verAngle=radonRes.getDipAngle();
        verAngle=10==verAngle?0:verAngle;
        verAngle=-10==verAngle?0:verAngle;
//        System.out.println("水平倾斜:"+dipAngle+"垂直倾斜:"+verAngle);
        destImage=rotationFilter.shearTransform(image,-dipAngle,-verAngle);

        middleSection=grayFilter.filter(destImage,null);
        BorderDetFilter borderDetFilter=new BorderDetFilter();
        ZoomFilter zoomFilter=new ZoomFilter();
        middleSection=zoomFilter.zoom(middleSection,440);
        middleSection=borderDetFilter.dealVerBlank(middleSection,false);
        binaryFilter.setThresholdType(BinaryFilter.SHIFT_THRESHOLD);
        middleSection=binaryFilter.filter(middleSection,null);
        middleSection=borderDetFilter.dealHorBorder(middleSection);
        return middleSection;
    }
    /**
     * 车牌字符分割
     * @param image
     * @return
     */

    public List<ExcisionUnit> charExc(BufferedImage image){
        ZoomFilter zoomFilter=new ZoomFilter();
        zoomFilter.setNewHeight(90);
        zoomFilter.setNewWidth(440);
        BufferedImage middleSection=zoomFilter.zoom(image);
        BorderDetFilter borderDetFilter=new BorderDetFilter();
        // 高通滤波除噪
        middleSection=borderDetFilter.dealSPCCharacter(middleSection);
        PhotoExcision photoExcision=new PhotoExcision();
        List<ExcisionUnit> excisions=photoExcision.doExcision(middleSection);
        excisions=NormalizationFactory.normalize(excisions);
        return excisions;
    }

    public void paintCharExcRes(){
        Graphics2D g2d=(Graphics2D)jPanel4.getGraphics();
        if(null==excisions) return;
        int width,height;
        ZoomFilter zoomFilter=new ZoomFilter();
        Iterator<ExcisionUnit> ite=excisions.iterator();
        int i=0;
        while (ite.hasNext()){
            ExcisionUnit excisionUnit=ite.next();
            if(excisionUnit==null) continue;
            width=excisionUnit.getWidth();
            height=excisionUnit.getHeight();
            BufferedImage temp=new BufferedImage(width,height,BufferedImage.TYPE_INT_RGB);
            AbstractBufferedImageOp.setRGB(temp,0,0,width,height,excisionUnit.getPixels());
            zoomFilter.zoom(temp,45);
            g2d.drawImage(temp,i*52,0,45,90,this);
            i++;
        }
        ite=excisions.iterator();
        i=0;
        zoomFilter.setNewWidth(45);
        zoomFilter.setNewHeight(90);
        while (ite.hasNext()){
            g2d=(Graphics2D)stdCharsPanel[i].getGraphics();
            ExcisionUnit excisionUnit=ite.next();
            if(excisionUnit==null) continue;
            width=excisionUnit.getWidth();
            height=excisionUnit.getHeight();
            BufferedImage temp=new BufferedImage(width,height,BufferedImage.TYPE_INT_RGB);
            AbstractBufferedImageOp.setRGB(temp,0,0,width,height,excisionUnit.getPixels());
            g2d.drawImage(temp,20,0,45,90,this);
            stdChars[i]=temp;
            i++;
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton10;
    private JButton jButton11;
    private JButton jButton3;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton4;
    private JButton jButton7;
    private JButton jButton8;
    private JButton jButton5;
    private JButton jButton12;
    private JButton[] saveBtns=new JButton[7];


    private JComboBox<String> jComboBox1;
    private JComboBox<String> jComboBox2;
    private JComboBox<String> jComboBox4;
    private JComboBox<String> jComboBox5;
    private JComboBox<String> jComboBox7;
    private JComboBox<String> jComboBox8;
    private JComboBox<String> jComboBox9;
    private JComboBox<String>[] cbbs=new JComboBox[7];
    private JLabel jLabel1;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel26;
    private JLabel jLabel27;
    private JLabel jLabel28;
    private JLabel jLabel29;
    private JLabel jLabel30;
    private JLabel jLabel31;
    private JLabel jLabel32;
    private JLabel jLabel33;
    private JLabel jLabel34;
    private JLabel jLabel6;
    private JPanel jPanel1;
    private JPanel jPanel14;
    private JPanel jPanel16; //字符1
    private JPanel jPanel17; //字符2
    private JPanel jPanel25;//字符3
    private JPanel jPanel27;//字符6
    private JPanel jPanel31;//字符4
    private JPanel jPanel33;//字符5
    private JPanel jPanel35;//字符7
    private JPanel[] stdCharsPanel=new JPanel[7];
    private JPanel jPanel2;
    private JPanel jPanel24;
    private JPanel jPanel26;
    private JPanel jPanel3;
    private JPanel jPanel30;
    private JPanel jPanel32;
    private JPanel jPanel34;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField4;
    private JTextField jTextField5;
    private JTextField jTextField7;
    private JTextField jTextField8;
    private JTextField jTextField9;
    private JTextField[] texts=new JTextField[7];
    // End of variables declaration//GEN-END:variables
}
